name = "xmessager-backend"
main = "src/index.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "xmessager-db"
database_id = "592e201c-44e9-42a0-8c09-e9a4fea1b834"

[vars]
HF_DATASET_REPO = "Spacklight/Video-data"
